version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sustentaguia
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sustentaguia_db/db_scripts:/docker-entrypoint-initdb.d/

  backend:
    build:
      context: ./sustentaguia_backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/sustentaguia
      SECRET_KEY: default_secret_key
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["npm", "start"]

  frontend:
    build:
      context: ./sustentaguia_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    entrypoint: ["npm", "start"]

volumes:
  db_data:
