version: '3.9'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: sustentaguia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sustentaguia_db/db_scripts:/docker-entrypoint-initdb.d/
    mem_limit: 512m

  backend:
    build:
      context: ./sustentaguia_backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sustentaguia
      SECRET_KEY: default_secret_key
      NODE_ENV: production
    ports:
      - "0.0.0.0:3001:3001"
      - "0.0.0.0:3002:3002"
      - "0.0.0.0:3003:3003"
      - "0.0.0.0:3004:3004"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    mem_limit: 512m

  frontend:
    build:
      context: ./sustentaguia_frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    entrypoint: ["npm", "start"]
    mem_limit: 1g

volumes:
  db_data:
